
version: 2

models:
  - name: ptolemy_test
    description: "Temporary scaffold"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
